apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: echo2
  namespace: default # as defined in meshConfig resource.
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY # will match outbound listeners in all sidecars
    patch:
      operation: INSERT_BEFORE
      value:
        name: "echo2"
        config:
